# Generated by Django 5.2.5 on 2025-08-29 04:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='new_marks',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='old_marks',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='portal.teacher'),
        ),
        migrations.AlterField(
            model_name='sessiontoken',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='portal.teacher'),
        ),
        migrations.AlterField(
            model_name='student',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='portal.teacher'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['teacher', '-timestamp'], name='portal_audi_teacher_e5eebe_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['action'], name='portal_audi_action_dc37bc_idx'),
        ),
        migrations.AddIndex(
            model_name='sessiontoken',
            index=models.Index(fields=['token'], name='portal_sess_token_eb6e85_idx'),
        ),
        migrations.AddIndex(
            model_name='sessiontoken',
            index=models.Index(fields=['expires_at'], name='portal_sess_expires_5aee2b_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['teacher', 'name'], name='portal_stud_teacher_c7e535_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['teacher', 'subject'], name='portal_stud_teacher_35be7d_idx'),
        ),
    ]
